version: '3.9'

services:
  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:16-alpine # Usamos la versión Alpine (más ligera)
    container_name: container_DB_FastOps
    restart: always # Si falla, se reinicia sola
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Usuario (lee de .env o usa default)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Contraseña
      POSTGRES_DB: ${POSTGRES_DB} # Nombre de la BD
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432" # Puerto PC : Puerto Contenedor
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network
    volumes:
      - postgres_data_volumen_fastops:/var/lib/postgresql/data # Persistencia de datos
  backend:

    build: ./backend # Aquí está tu Dockerfile del backend
    container_name: backend_FastOps
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Variables de Base de Datos
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres_network

    volumes:
      # Hot reload en desarrollo (eliminar en producción)
      - ./backend:/app
      # Excluir directorios que no deben sincronizarse
      - /app/__pycache__
      - /app/.pytest_cache

# ==========================================
# Volúmenes
# ==========================================
volumes:
  postgres_data_volumen_fastops:
    driver: local
    name: postgres_data_volumen_fastops

# ==========================================
# Redes
# ==========================================
networks:
  postgres_network:
    driver: bridge
    name: postgres_network
