version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    container_name: cesar_test_db
    environment:
      POSTGRES_USER: cesar_test_user
      POSTGRES_PASSWORD: cesar_test_password
      POSTGRES_DB: cesar_test_db
    ports:
      - "5433:5432" # Usamos puerto alterno 5433 para no chocar con produccion
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cesar_test_user -d cesar_test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      # No necesitamos persistencia real para tests, puede ser volatil
      - test_postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: backend_FastOps_Test
    restart: always
    ports:
      - "8001:8000"
    environment:
      POSTGRES_USER: cesar_test_user
      POSTGRES_PASSWORD: cesar_test_password
      POSTGRES_DB: cesar_test_db
      DATABASE_URL: postgresql://cesar_test_user:cesar_test_password@test-db:5432/cesar_test_db
      ALGORITHM: HS256
      SECRET_KEY: test_secret_key_123
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - ../backend:/app

volumes:
  test_postgres_data:
